import React, { ReactNode } from 'react';
import { LaptopOutlined, NotificationOutlined, UserOutlined, DownOutlined } from '@ant-design/icons';
import type { MenuProps } from 'antd';
import Image  from 'next/image';
import { Breadcrumb, Layout as AntdLayout, Menu, Dropdown, Space, message } from 'antd';

import styles from './index.module.css'
import { useRouter } from 'next/router';
import Head from "next/head";
import { Inter } from "next/font/google";
import Link from 'next/link';
import { logout } from '@/api/user';

const { Header, Content, Sider } = AntdLayout;

const inter = Inter({ subsets: ["latin"] });

const ITEMS = [
    {
        key: `accessory`,
        //icon: React.createElement(icon),
        label: `Accessories Management`,

        children: [ 
            {label: `Accessory List`, key: `/accessory` }, 
            {label: `Accessory Add`, key: `/accessory/add` },
        ], 
    },

    {
        key: `borrow`,
        //icon: React.createElement(icon),
        label: `Borrow Management`,

        children: [ 
            {label: `Borrow List`, key: `/borrow` }, 
            {label: `Borrow Add`, key: `/borrow/add` },
        ], 
    },

    {
        key: `category`,
        //icon: React.createElement(icon),
        label: `Category Management`,

        children: [ 
            {label: `Category List`, key: `/category` }, 
            {label: `Category Add`, key: `/category/add` },
        ], 
    },

    {
        key: `user`,
        //icon: React.createElement(icon),
        label: `Users Management`,

        children: [ 
            {label: `User List`, key: `/user` }, 
            {label: `User Add`, key: `/user/add` },
        ], 
    },
];

export function Layout({ children }: { children: ReactNode }) {
    const router = useRouter();
    const handleMenuClick: MenuProps["onClick"] = ({ key }) => {
      router.push(key);
    }

    const USER_ITEMS: MenuProps['items'] = [
      {
        key: '1',
        label: <Link href="/user/edit/">User Center</Link>,
      },
      {
        key: '2',
        label: <span onClick={async() => {
          await logout();
          message.success("Log out successfully");
          router.push('/login')
        }}>Log out</span>
      },
    ];

    const activeMenu = router.pathname

    return (
      <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <AntdLayout>
          <Header className={styles.header}>
            <Image src="/logo.jpeg" width={60} height={60} alt="" className={styles.logo} />
            Gym Accessory Management System
            <span className={styles.user}>
              <Dropdown menu={{ items:USER_ITEMS }}>
                <a onClick={(e) => e.preventDefault()}>
                  <Space>
                    User
                    <DownOutlined />
                  </Space>
                </a>
              </Dropdown>
            </span>
          </Header>
          <AntdLayout className={styles.sectionInner}>
            <Sider width={200} >
              <Menu
                mode="inline"
                defaultSelectedKeys={['/accessory']}
                defaultOpenKeys={['accessory']}
                selectedKeys={[activeMenu]}
                style={{ height: '100%', borderRight: 0 }}
                items={ITEMS}
                onClick={handleMenuClick}
              />
            </Sider>
            <AntdLayout className={ styles.sectionContent }>
              <Content className={ styles.content }>
                {children}
              </Content>
            </AntdLayout>
          </AntdLayout>
        </AntdLayout>
      </main>
    </>
  )
}